### ISSUE TITLE
What is Sleeping Money

### ISSUE THREAD

**Issue by timonson** [lj-n/genug-legacy#156]
Hello,

I got your service running according to your documentation. But I can't login with the credentials passed to docker. Do you have an idea why? But I was able to create a new user with the frontend.

Would you mind telling me what "Sleeping Money" means? I don't understand this calculation.
And why is it `Personal -4,00 €`?

![2-screenshot-2024-03-30](https://github.com/lj-n/genug/assets/54777088/0a177f78-46ca-4bc1-8f7e-2e6e91722d88)

Thanks!

**Comment by lj-n** [comment]
Hi, I will look into the credentials issue as soon as I have the time.
I will also write a detailed documentation on how to actually use the app :)

In the meantime : 

The philosophy is that each euro/dollar has a task and is assigned to a category. The `Sleeping Money` is the `sum of all transactions without a category` minus `the sum of all budgeted money`.

The result is the money that has not been distributed in any budget and is not assigned to any category, ergo `Sleeping Money`

This is calculated for the user (Personal) and for each team to which the user belongs.

In your case it is -4.00 because you have budgeted 4.00 in food but had no `Sleeping Money` to set the 4.00 Groceries budget.

**Comment by timonson** [comment]
Hi, thank you!
Like you pointed out, I think the *Sleeping Money* issue needs some more clarification or the change or addition of words.
If you have time and are interested I would like to talk to you about your project. I am interested in it and I could give you some important feedback. You can either contact me via discord `.timonson` or via email `timo@zaubrik.de`.
